pipeline:
  build:
    image: node:9-stretch
    commands:
      - apt update
      - apt install -y zip wine
      - yarn install
      - yarn dist
      - for f in assignment-*; do zip -r $f.zip $f; done
    when:
      event: tag
  release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - assignment-*
    when:
      event: tag
