pipeline:
  build:
    image: node:9-stretch
    commands:
      - apt update
      - apt install zip
      - yarn install
      - yarn dist
      - for f in assignment-*; do zip -r $f.zip $f; done
  release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - assignment-*
    when:
      event: tag
