pipeline:
  build:
    image: node:9-stretch
    commands:
      - dpkg --add-architecture i386
      - apt-get update
      - apt-get install -y zip wine wine32
      - yarn install
      - yarn dist
      - for f in assignment-*; do zip -r $f.zip $f; done
    when:
      event: tag
  release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - assignment-*.zip
    when:
      event: tag
